[project]
name = "calculuscalculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "latex2sympy>=1.0.3",
    "latex2sympy2>=1.9.1",
    "manim>=0.19.0",
    "sympy>=1.14.0",
]
